### ISSUE TITLE
Why does not Petterns.Clock contain U+1F55B🕛 ?

### ISSUE THREAD

**Issue by kzrnm** [mayuki/Kurukuru#14]
https://github.com/mayuki/Kurukuru/blob/7b3faa8e418eeab52d846f0836751b6c2f598c49/Kurukuru/Patterns.cs#L672-L685

Petterns.Clock.Frames is from `U+1F550`🕐 to `U+1F55A`🕚.

**Comment by mayuki** [comment]
Thanks! This issue is fixed in v1.4.2
