### ISSUE TITLE
Visual Studio Code でのデバッグ実行時にエラーが発生

### ISSUE THREAD

**Issue by toras9000** [mayuki/Kurukuru#15]
日本語でも大丈夫でしょうか。

特定の状況にて、エラーが生ずる現象に遭遇しましたので報告させていただきます。

事象が発生する実行環境は .NET 6.0 / Windows 10 or 11 で、C# の拡張機能を入れたVisual Studio Code によってデバッグ実行している状況です。
Visual Studio Code 上で.NET向けのテンプレートから作成した launch.json をそのまま利用したデバッグ実行で発生させることができます。
例えば以下のようなコードでも再現が出来ます。

```
Kurukuru.Spinner.Start(String.Empty, () => { });
```

発生するエラー(例外)のコールスタックは以下のようなものとなります。
スタックトレース内に表れていますが、Console.CursorLeft の呼び出し中にエラーとなるようです。
なお、vscode 上のデバッグコンソールに接続されるためかと思いますが、このとき Console.IsInputRedirected/Console.IsOutputRedirected はいずれも true となっています。

```
例外が発生しました: CLR/System.IO.IOException
型 'System.IO.IOException' のハンドルされていない例外が Kurukuru.dll で発生しました: 'ハンドルが無効です。'
   場所 System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   場所 System.ConsolePal.GetCursorPosition()
   場所 System.Console.get_CursorLeft()
   場所 Kurukuru.Spinner.Render(String terminator)
   場所 Kurukuru.Spinner.Stop(String text, String symbol, Nullable`1 color, String terminator)
   場所 Kurukuru.Spinner.Stop(String text, String symbol, Nullable`1 color)
   場所 Kurukuru.Spinner.Succeed(String text)
   場所 Kurukuru.Spinner.Start(String text, Action`1 action, Pattern pattern, Pattern fallbackPattern)
   場所 Kurukuru.Spinner.Start(String text, Action action, Pattern pattern, Pattern fallbackPattern)
   場所 Program.<Main>$(String[] args) (D:\temp\test\Program.cs):行 1
```

**Comment by mayuki** [comment]
ありがとうございます。コンソールがリダイレクトされている場合にカーソル位置などを触ってしまっていたので修正し、1.4.1としてリリースしました。

**Comment by toras9000** [comment]
対応いただきありがとうございます。
1.4.1 にて該当環境でエラーなく実行できることを確認できました。
